export SETTINGS='config.DevelopmentConfig'
export DATABASE_URL='postgresql://localhost/cases'
export DECISION_URL='http://decision.landregistry.local'
export MINT_URL='http://mint.landregistry.local/'
export SEARCH_URL='http://search-api.landregistry.local'
