"""empty message

Revision ID: 309c10f553c2
Revises: 4ecaa1f72b24
Create Date: 2014-09-12 15:12:58.918676

"""

# revision identifiers, used by Alembic.
revision = '309c10f553c2'
down_revision = '4ecaa1f72b24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('title', sa.TEXT(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'title')
    ### end Alembic commands ###
