"""empty message

Revision ID: 4ecaa1f72b24
Revises: 4e7f748ce0dc
Create Date: 2014-09-09 15:10:15.224626

"""

# revision identifiers, used by Alembic.
revision = '4ecaa1f72b24'
down_revision = '4e7f748ce0dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('request_details', sa.TEXT(), nullable=True))
    op.drop_column('cases', 'detail')
    op.alter_column('cases', 'work_queue',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'work_queue',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('cases', sa.Column('detail', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('cases', 'request_details')
    ### end Alembic commands ###
